### ISSUE TITLE
Doesn't work with Firefox 9.0.1 on Ubuntu 64

### ISSUE THREAD

**Issue by flosse** [talos/jquery-svgpan#1]
Console output:

```
Component returned failure code: 0x80004001 (NS_ERROR_NOT_IMPLEMENTED) [nsIDOMSVGSVGElement.getElementById]
```

This happens on line 376

**Comment by vmpartner** [comment]
Confirm, i have the same problem in Firefox 9.01 - Window 7. Maybe it will be helpful for @talos 
http://code.google.com/p/svgpan/issues/detail?id=13

**Comment by talos** [comment]
Thanks for the report.  I experienced the same issue when I upgraded Firefox to 9, but using jQuery to select instead of .getElementById on the SVG looks to solve the problem.  Working for me now, let me know if you have any problems.

@vmpartner Thanks for the reference, but jquery-svgpan eliminated the getRoot() function entirely (you must pass the root node explicitly), so this is not a concern.

**Comment by flosse** [comment]
Great! Now it works :)

**Comment by vmpartner** [comment]
@talos, thank's a lot for this script ;)
