### ISSUE TITLE
Error showing demo with Firefox 14.0.1

### ISSUE THREAD

**Issue by FlorianX** [talos/jquery-svgpan#8]
NS_ERROR_ILLEGAL_VALUE: Component returned failure code: 0x80070057 (NS_ERROR_ILLEGAL_VALUE) [nsIDOMSVGPoint.x]
http://blog.accursedware.com/jquery-svgpan/jquery-svgpan.js
Line 141

**Comment by talos** [comment]
This is related to the recent switchover to use `.offsetX`, which is not normalized in jQuery and thus not available in all browsers: http://bugs.jquery.com/ticket/8523

Looking into cross-browser solution and will resolve ASAP.

**Comment by talos** [comment]
The lack of a functioning `getBoundingClient()` for SVGs in Firefox is making this irritating: https://bugzilla.mozilla.org/show_bug.cgi?id=530985

**Comment by FlorianX** [comment]
What do you think about the Workaround: http://bugs.jquery.com/ticket/8523#comment:16

**Comment by talos** [comment]
Unfortunately, `.offset()` in jQuery uses `.getBoundingClient()`, which produces totally unpredictable values from SVGs in Firefox.  I think the problem may be isolated to instances where there is a transformation matrix active upon the SVG, but I have not been able to isolate any way to reverse the transformation and thus obtain a real value.

**Comment by talos** [comment]
This has been fixed with e23b6dcf7975a48b2ee771a41351552cd34bfe7e and the move to 0.1.4.  Due to FF's finicky behavior with the position of SVGs, it's only possible to use the workaround in certain cases, see:

https://github.com/talos/jquery-svgpan/blob/master/jquery-svgpan.js#L136

In the demo, FF generates correct values for the first SVG, but not the second.  In the case of the second, the workaround is to use the offset of the parent element, instead.
